### ISSUE TITLE
Fix warnings in post-testgrid-deploy-canary

### ISSUE THREAD

**Issue by chases2** [GoogleCloudPlatform/testgrid#1087]
https://oss.gprow.dev/view/gs/oss-prow/logs/post-testgrid-deploy-canary/1597371707859931136

```
$ /usr/bin/kubectl --kubeconfig= --cluster=gke_k8s-testgrid_us-central1_auto --context= --user= apply -f -
W1128 23:29:11.700812    3061 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```

**Comment by chases2** [comment]
/assign
@ankur12-1610 researched the initial fix, but I'll need to verify it with a deploy to canary.

**Comment by ankur12-1610** [comment]
> The warning is handled, see https://oss.gprow.dev/log?job=post-testgrid-deploy-canary&id=1632808438096465920. (The deprecation warning isn't there anymore)

Hey @chases2 I'm not able to see the deploy logs anymore:
![Screenshot from 2023-03-07 02-25-45](https://user-images.githubusercontent.com/76884959/223228875-6aefdbda-cbe9-4a54-8e30-87138ee0f9ce.png)
