### ISSUE TITLE
Pass flag or configuration params in structs instead of individually

### ISSUE THREAD

**Issue by michelle192837** [GoogleCloudPlatform/testgrid#1121]
In main.go for many of the TestGrid modules, we often call one or more functions and pass in a lot of parameters.

Ex: https://github.com/GoogleCloudPlatform/testgrid/blob/master/cmd/updater/main.go#L183
```
updater.Update(ctx, client, mets, opt.config, opt.gridPrefix, opt.groupConcurrency, opt.groups.Strings(), groupUpdater, opt.confirm, opt.wait, fixers...)
```

A lot of these options are options to configure how updates happen (how many groups to update in parallel, whether to update only specific groups, whether to write to storage, how long to wait between cycles, etc) and could be bundled into a single struct instead of keeping a long, ambiguous list of parameters passed into the function.

Files that would benefit:
[ ] [updater/main.go](https://github.com/GoogleCloudPlatform/testgrid/blob/master/cmd/updater/main.go)
[ ] [tabulator/main.go](https://github.com/GoogleCloudPlatform/testgrid/blob/master/cmd/tabulator/main.go)
[ ] [summarizer/main.go](https://github.com/GoogleCloudPlatform/testgrid/blob/master/cmd/summarizer/main.go)

**Comment by moki1202** [comment]
@michelle192837 I can pick up this issue if its fine :)

**Comment by michelle192837** [comment]
Sounds good to me! ^^

**Comment by moki1202** [comment]
@michelle192837 before pushing anything, I'll share a snippet here. Please let me know if I need to improve it.  Plus, I can't figure out the data type of fixers.

**Comment by moki1202** [comment]
```
type UpdateOptions struct {
	ctx  context.Context
	client  gcs.Opener
	mets   *Metrics
	config    gcs.Path
	gridPrefix     string
	groupConcurrency      int
	groups        util.Strings
	groupUpdater       GroupUpdater
	confirm        bool
	wait     bool
	fixers     <--don't know-->
}

u := UpdateOptions{
	ctx:    ctx,
	client:   client,
	mets:   mets,
	config:    opt.config,
	gridPrefix:    opt.gridPrefix,
	groupConcurrency:    opt.groupConcurrency,
	groups:     opt.groups.Strings(),
	groupUpdater:     groupUpdater,
	confirm:    opt.confirm,
	wait:    opt.wait,
	fixers:     fixers,
}   
if err := updater.Update(u UpdateOptions);                             
```

**Comment by moki1202** [comment]
Now I understand that `context` is a package that we import but what does `context.Context` mean here? Sorry if I sound vague.

**Comment by bweston92** [comment]
@moki1202 in Go we normally keep the `ctx` variable as the first params. For example `if err := updater.Update(ctx context.Context, u UpdateOptions);`.

**Comment by moki1202** [comment]
@bweston92 gotcha! other than that does everything else look fine?

**Comment by bweston92** [comment]
The members of `UpdateOptions` need to be exported so would need a capital letter on the first letter.

**Comment by michelle192837** [comment]
Things that are clients (`client`) or are complex (`groupUpdater`, `fixers`, possibly `mets`), I would keep in the function parameters as well. (And +1 to bweston92's comments above). The others look reasonable though. ^^
