### ISSUE TITLE
Remove use of 'grid path prefix' where it's no longer necessary

### ISSUE THREAD

**Issue by michelle192837** [GoogleCloudPlatform/testgrid#1123]
Updates used to go through the Updater (grab results, make a grid) to the Summarizer (summarize stats for a grid).

Now there's also Tabulator, so updates go from the Updater > Tabulator (turn a grid into the user-viewed grid) > Summarizer.

We still have some leftover flags or code though that are there from the migration to using the Tabulator module. For example:
- https://github.com/GoogleCloudPlatform/testgrid/blob/f325852c59aa08e560990644f772c7c04432c6ef/pkg/api/v1/state.go#L85 and https://github.com/GoogleCloudPlatform/testgrid/blob/f325852c59aa08e560990644f772c7c04432c6ef/pkg/api/v1/server.go#L32 (GridPrefixPath should never be set, we should be able to remove that setting and any code that uses it)
- https://github.com/GoogleCloudPlatform/testgrid/blob/18fbd6a6712adb48e2427daaa5b07752a0a63cc3/cmd/summarizer/main.go#L45 (same here, no need for gridPathPrefix)

**Comment by ankur12-1610** [comment]
@michelle192837 I would like to work on this as the current issue #1124 which I'm working on is almost solved.

**Comment by michelle192837** [comment]
Sounds good! Feel free to assign to yourself ^^

**Comment by ankur12-1610** [comment]
Sure
/assign
