### ISSUE TITLE
Add nanos to timestamp when converting

### ISSUE THREAD

**Issue by michelle192837** [GoogleCloudPlatform/testgrid#1124]
https://github.com/GoogleCloudPlatform/testgrid/blob/4d8396ffaf3e1df48f53a374ca7989af30678ce2/pkg/api/v1/summary.go#L181

We convert a double-typed timestamp to a proto timestamp (which has 'seconds' and 'nanos' fields), but we drop nanoseconds when doing so. Instead, add them when converting.

**Comment by ankur12-1610** [comment]
I would like to work on this issue!

**Comment by gunwant11** [comment]
@michelle192837  I can pick up this issue if its not assigned :)

**Comment by michelle192837** [comment]
Going to let first-come-first-serve apply here, so Ankur feel free to assign to yourself ^^ (I think `/assign` should work)

**Comment by ankur12-1610** [comment]
> Going to let first-come-first-serve apply here, so Ankur feel free to assign to yourself ^^ (I think `/assign` should work)

Got it!
