### ISSUE TITLE
test-grid not visible when there are a lot of jobs

### ISSUE THREAD

**Issue by neolit123** [GoogleCloudPlatform/testgrid#139]
hello, i've noticed that the kops project has added a lot of jobs to their dashboard, but it appears that in my browser (recent version of chrome) and desktop resolution (1600x900px) is not possible to see the actual test-grid even if scrolling.

screenshot:
![testgrid-kops](https://user-images.githubusercontent.com/331852/86153615-a0cbcf80-bb0a-11ea-868d-e85dcfc2636a.jpg)

link:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kops#kops-aws-arm64

**Comment by michelle192837** [comment]
Working on a fix to limit the line-height here. ^^

I'll also look at a documentation update with some tips to make a denser tab.

**Comment by michelle192837** [comment]
After a lot of CSS fussing, I have a fix for this that should go live sometime next week.

**Comment by michelle192837** [comment]
Alright, fix is submitted, and should be live tomorrow if there are no issues. ^^

**Comment by michelle192837** [comment]
This is in! It should be much easier to see tabs now.

If you want to combine tabs together, you can do so by listing multiple job paths in one test group (see https://github.com/GoogleCloudPlatform/testgrid/blob/master/config.md#test-groups, there's a commented example), though this works best _if your jobs run at the same commit_. You may need to adjust some other things too (like open_test_template and base_options); if so let me know and I can help configure that a bit.

**Comment by neolit123** [comment]
thanks @michelle192837 !
