### ISSUE TITLE
Prow Job IDs are incorrectly tool tipped as commits - fix or remove?

### ISSUE THREAD

**Issue by RobertKielty** [GoogleCloudPlatform/testgrid#159]
The Test Grid Column headers have the **Prow Job Run ID** which  are tool tipped as _commits_.

This is a UX pothole on the path to using the Commit Diff Click, Drag and Search as it misleads you into thinking that there are two different commits when there are not. 

So at the start of day I would scan the col headers, mouse over  two job ids, see that they are "commits" and then Click and Drag from one results cell to another only to have GH tell me that I'm diffing the same commit.

I'd argue for the removal of the Prow Job ID from the page entirely: 
The Job ID Col provides
- no functionality
- is noise rather than signal
- is a lot of DOM object rendering for no payback.

If I have a burning desire to know the Prowjob Run ID (I don't) all I have to do is click on any result cell to navigate to the job run and I'll see it at the top of the SpyGlass page.

I can imagine that it was useful during development and maybe there could be an argument for having the Job IDs present for
test-grid debugging purposes but for the end user there's not much use for them in seeing the Job ID.

If it's too much work to remove the Job ID as a header then it would be great if the tool tip was changed to be **Job ID**

**Comment by fejta** [comment]
Changing this to "build number"

**Comment by RobertKielty** [comment]
Saw this today, TYSM! Closing.
