### ISSUE TITLE
Preview the golang updater results

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/testgrid#211]
You can now see the results of the open-source golang updater processing your tabs (it will default to the python one).

Please link here to any odd tabs (and what is odd about them).

Toggle between the prod (aka python) and beta (aka open source golang) versions of the data by appending `&grid=beta` to the URL fragment.

AKA navigate somewhere at https://testgrid.k8s.io, open up a tab and then add `&grid=beta` to the end of the address bar, then by back by deleing this parameter and/or changing it to `&grid=old`:
* [Example](https://testgrid.k8s.io/sig-testing-misc#local-up-cluster,%20master%20(dev)&grid=beta)

**Comment by fejta** [comment]
Sent out notice that this is available: https://groups.google.com/g/kubernetes-dev/c/dF5h3XuDV7k

**Comment by detiber** [comment]
I tried viewing the Cluster API e2e tests using the new updater and it looks like it isn't showing the junit results broken out:
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi%20e2e%20tests&grid=old vs https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi%20e2e%20tests&grid=beta

**Comment by fejta** [comment]
Thanks for the report @detiber ! Corrected on canary (rolling out to prod soon): https://external-canary-dot-k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api#capi%20e2e%20tests&grid=beta

**Comment by tehcyx** [comment]
Hey @fejta,
Comparing https://testgrid.k8s.io/kyma_integration#post-kyma-release-upgrade with https://testgrid.k8s.io/kyma_integration#post-kyma-release-upgrade&grid=beta

I'm missing all the details of the individual tests of the suite that was run. Assuming it's the same or similar to what @detiber posted above.

**Comment by fejta** [comment]
This fix for this landed in production this afternoo, looks like things look better? https://testgrid.k8s.io/kyma_integration#post-kyma-release-upgrade&grid=beta

**Comment by tehcyx** [comment]
> This fix for this landed in production this afternoo, looks like things look better? https://testgrid.k8s.io/kyma_integration#post-kyma-release-upgrade&grid=beta

Indeed, in the old one there's still a deep link to the changes, as well as this note `Show 2 stale tests (no results in last 10+ runs)` with a link that doesn't seem to change whatever is displayed?

**Comment by fejta** [comment]
It does if you look carefully enough: it adds rows for kyma-system/core-console-backend-service and kyma-system/core-console, which haven't been around since May 29.

**Comment by tehcyx** [comment]
> 
> 
> It does if you look carefully enough: it adds rows for kyma-system/core-console-backend-service and kyma-system/core-console, which haven't been around since May 29.

Guess I didn't look close enough.

**Comment by fejta** [comment]
Thanks for the reports thus far! We've already found and fixed a couple issues. Please continuing to note anything amiss.

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-testing-misc#triage&graph-metrics=test-duration-minutes&width=5&grid=beta
![Screen Shot 2020-08-31 at 8 17 44 PM](https://user-images.githubusercontent.com/49258/91791070-08fc6780-ebc7-11ea-9312-24d19582c88b.png)

https://testgrid.k8s.io/sig-testing-misc#triage&graph-metrics=test-duration-minutes&width=5
![Screen Shot 2020-08-31 at 8 18 39 PM](https://user-images.githubusercontent.com/49258/91791126-29c4bd00-ebc7-11ea-9bad-9b05c0301e7f.png)

**Comment by fejta** [comment]
Aaron, the auto-generated metric for each row [changed](https://testgrid.k8s.io/sig-testing-misc#triage&graph-metrics=seconds-elapsed&width=5&grid=beta) to `seconds-elapsed`. (seconds is a better unit of measurement).

I'll make the frontend redirect you.

**Comment by deads2k** [comment]
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.6-informing#release-openshift-ocp-installer-e2e-ovirt-4.6 has a different set of tests than https://testgrid.k8s.io/redhat-openshift-ocp-release-4.6-informing#release-openshift-ocp-installer-e2e-ovirt-4.6&grid=old even though they are the same job.  Is this inconsistency expected?

**Comment by jeefy** [comment]
Seconding @deads2k -- I'm seeing similar behavior in my testgrid dashboards, but adding `&grid=old` resolves the issue.

**Comment by fejta** [comment]
Thanks! Should be all fixed up now. Please report any other odd behavior.

**Comment by fejta** [comment]
We will likely start disabling the python version here in a little bit, so please make sure you're not needing to use `&grid=old` (if you are let us know why so we can investigate) as that will stop working.

**Comment by spiffxp** [comment]
We're missing results for a number of merge-blocking kubernetes presubmits.  They show up on the old grid, but not the new version: https://github.com/kubernetes/test-infra/issues/19696#issuecomment-722606378

**Comment by michelle192837** [comment]
We appear to have an issue with this on GCE images too: https://k8s-testgrid.appspot.com/google-gce-compute-image-tools#ci-images-import-export-cli-e2e-tests&grid=old vs. https://k8s-testgrid.appspot.com/google-gce-compute-image-tools#ci-images-import-export-cli-e2e-tests&grid=beta.

**Comment by michelle192837** [comment]
This seems to be more widespread than just one dashboard, and is affecting at least multiple dashboards.

Reminder: To view more recent results if your dashboard isn't showing recent ones, please append `&grid=old` to the URL!
