### ISSUE TITLE
vbom.ml seems to be down

### ISSUE THREAD

**Issue by chmouel** [GoogleCloudPlatform/testgrid#228]
When trying to import testgrid this will try to import this module from vbom.ml : 

https://github.com/GoogleCloudPlatform/testgrid/blob/master/go.mod#L19

but the host is down : 

```
	vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml: no such host
```

**Comment by fejta** [comment]
`go get vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787` worked for me just now
