### ISSUE TITLE
Email alerts for failing tests always have the datetime Mon Jan 19 5:01PST

### ISSUE THREAD

**Issue by thejoycekung** [GoogleCloudPlatform/testgrid#244]
Specifically for k8s TestGrid, at least.
![image](https://user-images.githubusercontent.com/13409103/95366409-690abb80-08a1-11eb-8227-bcac097b8bfe.png)

Note that the commits seem correct though, it's just the date and time.

**Comment by michelle192837** [comment]
Fix for this is submitted, and should be live on the next release (prob. tomorrow unless something goes wrong).

**Comment by thejoycekung** [comment]
Looks like it's working great now. Thanks @michelle192837 ! 

![image](https://user-images.githubusercontent.com/13409103/95622504-a27a2d00-0a41-11eb-9c69-d138f8c220e9.png)

**Comment by michelle192837** [comment]
Awesome, thanks for verifying! :D
