### ISSUE TITLE
TestGrid displaying jobs as "running" when they should be "passed"

### ISSUE THREAD

**Issue by thejoycekung** [GoogleCloudPlatform/testgrid#248]
Hopefully this is in the right repo. Let me know if it should be logged over in k/test-infra instead.

This is an example of what the board looks like with this issue - this is [sig-release-master-blocking/gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&sort-by-flakiness=).
![image](https://user-images.githubusercontent.com/13409103/95643154-4c29e000-0a7b-11eb-8349-c03f31fcf797.png)

If we dig into those tests, the `prowjob.json` says that the status is `success` with the description `Job succeeded`.
Example spyglass link here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1314664037685923840

Happening since ~8AM PT on Friday.

**Comment by thejoycekung** [comment]
As of ~10AM PT on Monday (12th) it looks like this stopped happening. Would still love to know why this happened though!

![image](https://user-images.githubusercontent.com/13409103/95878339-1a4a9f00-0d43-11eb-88b0-1c3faadb7a6f.png)

**Comment by michelle192837** [comment]
Hi! Thanks for filing and updating, sorry about the delayed response. The root cause was a change that combined previous statuses when accumulating the current status for a test, which caused Running to get folded in to more recent statuses when it should be overwritten. (Culprit change was identified and rolled back now, so it shouldn't affect any results going forward, though it will stay for some older results unfortunately.)

**Comment by thejoycekung** [comment]
Thanks for the explanation Michelle! Going to go ahead and close this issue now.

**Comment by thejoycekung** [comment]
@michelle192837 It looks like this might still be affecting some jobs? Here's gce-master-scale-correctness on the sig-release-master-informing: https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

Example spyglass links: 

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1317073285288038400
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1316348499561811968 <-- this one is a "failure" but it's still labeled as running on TestGrid.

![image](https://user-images.githubusercontent.com/13409103/96276503-1ae07100-0fa1-11eb-91dd-6b2bf6207e55.png)

**Comment by thejoycekung** [comment]
Closing again because it seems to have resolved.
