### ISSUE TITLE
testgrid showing tests as failed when they flaked

### ISSUE THREAD

**Issue by deads2k** [GoogleCloudPlatform/testgrid#250]
Looking at https://testgrid.k8s.io/redhat-openshift-ocp-release-4.6-informing#release-openshift-origin-installer-e2e-gcp-upgrade-4.5-stable-to-4.6-ci and if you click on the runs on 10/10 that show several failed tests.  The individual job run actually claims those tests flaked, not failed.

Another example is  https://testgrid.k8s.io/redhat-openshift-ocp-release-4.6-informing#release-openshift-ocp-installer-e2e-gcp-rt-4.6&grid=old .  clicking on https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-rt-4.6/1316318236362412032 show flaky tests, but the testgrid shows red bubbles, not purples

There is a slack thread here https://kubernetes.slack.com/archives/C09QZ4DQB/p1602618531246100 to get in touch with me if there's more info I can provide.

**Comment by fejta** [comment]
The golang updater appear to do the right thing here.
