### ISSUE TITLE
Use consistent protos everywhere

### ISSUE THREAD

**Issue by michelle192837** [GoogleCloudPlatform/testgrid#26]
Some of these are already handled, some are partially exposed, some we don't have a ready solution for (config.proto). These are the formats that TestGrid uses throughout the updaters/frontend, so we want to update them in one place instead of porting new changes out inconsistently.

As of November 12, 2019:
- [ ] config.proto
  - [x] ...is in GCP/testgrid
  - [ ] ...is the source of truth
- [x] issue_state.proto
  - [x] ...is in GCP/testgrid
  - [x] ...is the source of truth
- [ ] state.proto
  - [x] ...is in GCP/testgrid
  - [ ] ...is the source of truth
- [x] summary.proto
  - [x] ...is in GCP/testgrid
  - [x] ...is the source of truth
- [x] test_status.proto
  - [x] ...is in GCP/testgrid
  - [x] ...is the source of truth
- [x] custom_evaluator.proto
  - [x] ...is in GCP/testgrid
  - [x] ...is the source of truth

**Comment by fejta** [comment]
This one still WIP?

**Comment by michelle192837** [comment]
Yup, config.proto is being a jerk. We could probably switch state.proto over at least.
