### ISSUE TITLE
Add Job Owner and JobConfig reference to TestGrid results page for testgrid.k8s.io

### ISSUE THREAD

**Issue by RobertKielty** [GoogleCloudPlatform/testgrid#261]
## New feature request

As a **testgrid.k8s.io TestGrid user**, viewing a Test Grid Job Results page, I should be able to

1. view the **configured Job Owner** if present
2. easily navigate to the **CI job configuration** associated with the results 

## Rationale
Makes reporting and escalation of flaking/failing tests easier for CI Signal monitors and developers wishing to make test fix contributions

## Current behavior
**About** > **View configuration** menu 
navigates to  

https://testgrid.k8s.io/q/config/sig-release-master-blocking/bazel-test-master

and produces the following response

_config query is not yet supported in external versions_

## Mitigation / workaround

1. On the results page, select and copy whatever Job Description appears above the options menus 
2. Goto https://cs.k8s.io/
3. Paste the selected text as a search
4. Press enter 
5. Navigate to the job file.

**Comment by chases2** [comment]
The About > View configuration behavior has been fixed; `q/config` links now work externally. This gives two-click access to the alert emails configured for this job.

Independently, an improvement to Configurator has made the description auto-generated from Prow instances more verbose. https://github.com/kubernetes/test-infra/pull/20844. This includes a link to the ProwJob's configuration as well as the TestGrid configuration. (Thanks, @spiffxp!)

If there's some other enhancement that could help this use case, please reopen this issue with further details.
