### ISSUE TITLE
ppc64le-unit has large numbers of empty rows

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/testgrid#312]
https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests why does this show 27k stale rows, which seem to have never had any results?

/assign

**Comment by fejta** [comment]
ref https://github.com/kubernetes/test-infra/issues/20010

**Comment by Rajalakshmi-Girish** [comment]
@fejta I now see the results updated till 21-12-2020, unlike yesterday only till 11-12-2020. Please let me know if anything changed that caused these runs to be updated?

Also, the 27k stale rows are due to the "periodic-kubernetes-bazel-test-ppc64le" prow jobs that are stuck in running state for a long time. I shall look into this.

@mkumatag

**Comment by fejta** [comment]
Yes https://github.com/GoogleCloudPlatform/testgrid/pull/311 which had a mitigation for this scenario (a very wide and tall grid)

**Comment by fejta** [comment]
> "periodic-kubernetes-bazel-test-ppc64le" prow jobs that are stuck in running state for a long time

+1 to looking your looking into any issues you may be having with your jobs but I do think this is a testgrid processing issue (note that they do not appear on &grid=old, right?)

**Comment by fejta** [comment]
Yep, nothing wrong on your end (we already handle the scenario where jobs never finish, we just need to drop rows that get renamed, see linked PR)

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> > "periodic-kubernetes-bazel-test-ppc64le" prow jobs that are stuck in running state for a long time
> 
> +1 to looking your looking into any issues you may be having with your jobs but I do think this is a testgrid processing issue (note that they do not appear on &grid=old, right?)

The empty rows do appear even in &grid=old. Please see below:
![image](https://user-images.githubusercontent.com/63038004/102886104-81d74600-447a-11eb-9cc3-04d543f32e0c.png)

**Comment by fejta** [comment]
That shows a column that never finished, with a most of the rows empty on that particular column.

The problem here was the "Show 2 stale tests" link, which was actually showing 27000 rather than 2 (see [here](https://github.com/kubernetes/test-infra/issues/20010#issuecomment-748937585)). 

The 2 stale results are also not a problem, if you expand and scroll back to Dec 11 you'll see that //test/e2e/storage/testsuites possibly moved to //test/e2e/storage/utils -- eventually those two will clean up.

The problem is when you expanded the 27000 results: a) this was slow because we had to process 28000 rows per column instead of 1000 and more importantly b) those 27000 results did not have any column in which they were non-empty.

PS: that result is correctly reported as a timed out error at head https://testgrid.k8s.io/sig-node-ppc64le#unit-tests&show-stale-tests=

**Comment by Rajalakshmi-Girish** [comment]
@fejta Thanks for the detailed explanation 👍
