### ISSUE TITLE
Junit report mark "error" testcase as success

### ISSUE THREAD

**Issue by qinqon** [GoogleCloudPlatform/testgrid#408]
At junit reporting there a part from "failure" there is "error" testcases that need to be marked as failure, currectly they are marked as success, this fix illustrate the issue https://github.com/GoogleCloudPlatform/testgrid/pull/406

**Comment by fejta** [comment]
/assign @qinqon @michelle192837 

Do either of you two plan to finish the work started in #406?

**Comment by michelle192837** [comment]
I'm happy to take it next week if @qinqon isn't planning to. ^^

**Comment by qinqon** [comment]
@michelle192837 @fejta I prefer on focus test grid dep at Prow spyglass to fix a big is affecting us at kubevirt.
