### ISSUE TITLE
Testgrid dashboard isn't showing the correct data

### ISSUE THREAD

**Issue by jsturtevant** [GoogleCloudPlatform/testgrid#413]
The testgrid dashboard tab for https://testgrid.k8s.io/sig-windows-master-release#gce-windows-2019-containerd-master is showing it hasn't been updated since 3/23 but the job seems to be running https://prow.k8s.io/?job=ci-kubernetes-e2e-windows-containerd-gce

Testgrid:
![Screenshot from 2021-04-02 11-44-17](https://user-images.githubusercontent.com/648372/113444457-cabb6680-93a8-11eb-987f-62617d26a122.png)

Jobs running:

![Screenshot from 2021-04-02 11-45-00](https://user-images.githubusercontent.com/648372/113444515-e58ddb00-93a8-11eb-8775-77257f07a8ba.png)

Looks like there was invalid xml uploaded: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-containerd-gce/1374430664555761664

Slack thread: https://kubernetes.slack.com/archives/C7J9RP96G/p1617386737023200

/assign @fejta

**Comment by fejta** [comment]
https://testgrid.k8s.io/q/config/sig-windows-master-release/gce-windows-2019-containerd-master

```
***TEST GROUP CONFIG***:

name:  "ci-kubernetes-e2e-windows-containerd-gce"
```

**Comment by fejta** [comment]
https://external-canary-dot-k8s-testgrid.appspot.com/sig-windows-master-release#gce-windows-2019-containerd-master

will soon be visible in prod too
