### ISSUE TITLE
TestGrid dashboard header links don't turn red when failing

### ISSUE THREAD

**Issue by chaodaiG** [GoogleCloudPlatform/testgrid#442]
Referenced from https://github.com/knative/test-infra/issues/2764

A little context: 

- Knative is a tenant of k8s prow as https://testgrid.k8s.io/r/knative-own-testgrid
- The set up is decribed at https://github.com/GoogleCloudPlatform/testgrid/blob/master/standalone.md#standalone-testgrid-fe-for-knative-prow
-

**Comment by chaodaiG** [comment]
Settings are at https://github.com/knative/test-infra/blob/main/config/prod/prow/k8s-testgrid/testgrid-common-settings.yaml

**Comment by fejta** [comment]
See referenced issue
