### ISSUE TITLE
Update the resultstore exporter to work with searching

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/testgrid#45]
We should be able to search resultstore for to find any prowjob that matches obvious fields like repo, job name, PR, etc.

/assign

**Comment by fejta** [comment]
cc @tony-yang

**Comment by tony-yang** [comment]
Thanks for adding me here Erick. Will take a look once all test result properties are uploaded to resultstore.

**Comment by fejta** [comment]
/assign @tony-yang 

Shall we call this fixed?

**Comment by tony-yang** [comment]
Not yet, WIP. Once I have this done and documented, I'll update it here. Thanks.

**Comment by tony-yang** [comment]
PR https://github.com/GoogleCloudPlatform/testgrid/pull/111

**Comment by tony-yang** [comment]
@fejta This is done. Feel free to close this issue. Thanks.

**Comment by fejta** [comment]
Any instructions on how to search?

**Comment by tony-yang** [comment]
Thanks Erick. I added a README for the resultstore client.
