### ISSUE TITLE
Testgrid summary page shows outdated info

### ISSUE THREAD

**Issue by jsturtevant** [GoogleCloudPlatform/testgrid#453]
The summary page for sig-windows (https://testgrid.k8s.io/sig-windows-signal) is showing outdated info:

![Screenshot from 2021-05-03 10-18-21](https://user-images.githubusercontent.com/648372/116909430-0f7d2c00-abf9-11eb-8c0f-1b9a98c3c882.png)

but the dashboard is green (https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master)

![Screenshot from 2021-05-03 10-21-32](https://user-images.githubusercontent.com/648372/116909648-5f5bf300-abf9-11eb-9695-4914ff6cf505.png)

The `last_update_timestamp` https://testgrid.k8s.io/sig-windows-signal/summary is currently: 1619639102 (Wed Apr 28 2021 19:45:02) 

```
curl https://testgrid.k8s.io/sig-windows-signal/summary | jq ".[\"aks-engine-windows-containerd-master\"]"
{
  "alert": "",
  "last_run_timestamp": 1619632613000,
  "last_update_timestamp": 1619639102,
  "latest_green": "dc6b04c14",
  "overall_status": "FLAKY",
  "overall_status_icon": "remove_circle_outline",
  "status": "7 of 10 (70.0%) recent columns passed (2425 of 2432 or 99.7% cells)",
  "tests": [],
  "dashboard_name": "sig-windows-signal",
  "healthiness": {
    "tests": [],
    "previousFlakiness": -1
  }
}
```

**Comment by CecileRobertMichon** [comment]
+1 seeing the same thing on the sig-cluster-lifecycle dashboards https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure

**Comment by fejta** [comment]
Seems likely related to this release: https://github.com/GoogleCloudPlatform/testgrid/pull/444

**Comment by jsturtevant** [comment]
Thanks! Looks like #458 fixed most of it.  I noticed some have 10/10 but are not green:

![image](https://user-images.githubusercontent.com/648372/117067598-14b4a680-acdf-11eb-83b5-4fab970bf989.png)

**Comment by fejta** [comment]
That's interesting! Will move to a separate issue
