### ISSUE TITLE
Newly created tab's group not found

### ISSUE THREAD

**Issue by rifelpet** [GoogleCloudPlatform/testgrid#551]
A new prow job was added 2 days ago to the k8s testgrid instance. Its tab is still grey and returns a "group not found" error. Viewing the job's logs [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-keypair-rotation) confirm there have been numerous invocations over the past 2 days. The error says to file an issue but I wasn't sure whether to do it here or in test-infra, so let me know if I need to move this or if there is anything wrong with the new job's configuration. Thanks! 

https://testgrid.k8s.io/kops-misc#kops-aws-keypair-rotation

https://github.com/kubernetes/test-infra/pull/22927

<img width="1165" alt="Screen Shot 2021-07-18 at 7 42 34 AM" src="https://user-images.githubusercontent.com/1455650/126071504-db5dd00b-eba4-40d6-8b6b-111e9fa9f89f.png">

**Comment by chases2** [comment]
The config is there: https://testgrid.k8s.io/q/config/kops-misc/kops-aws-keypair-rotation
...and it looks like the config for a [neighboring tab](https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller-irsa) that is working fine: https://testgrid.k8s.io/q/config/kops-misc/kops-aws-aws-load-balancer-controller-irsa

**Comment by michelle192837** [comment]
e2e-kops-aws-keypair-rotation doesn't seem to show up in the Updater logs, but e2e-kops-aws-aws-load-balancer-controller-irsa does just fine. :/

**Comment by fejta** [comment]
I believe this is because these jobs are frequently OOMing

**Comment by fejta** [comment]
This is showing up in canary: https://external-canary-dot-k8s-testgrid.appspot.com/kops-misc#kops-aws-keypair-rotation and should soon in prod
