### ISSUE TITLE
Successful prow job showed red `pod` on testgrid 

### ISSUE THREAD

**Issue by chaodaiG** [GoogleCloudPlatform/testgrid#656]
https://testgrid.k8s.io/googleoss-test-infra#autobump-prow-for-auto-deploy

![Screen Shot 2021-08-18 at 11 09 09 AM](https://user-images.githubusercontent.com/45011425/129950041-ec32831d-53c6-4741-9e2a-8f572c4d2cb3.png)

the prow job with red `pod` is https://oss-prow.knative.dev/view/gs/oss-prow/logs/ci-oss-test-infra-autobump-prow-for-auto-deploy/1428054460566867968

**Comment by chaodaiG** [comment]
also happened at https://testgrid.k8s.io/sig-testing-prow#push-prow

**Comment by fejta** [comment]
```
   77  2021-08-18T18:02:09Z  gs://oss-prow/logs/ci-oss-test-infra-autobump-prow-for-auto-deploy/1428054460566867968/finished.json#1629309729931792
24092  2021-08-18T18:02:28Z  gs://oss-prow/logs/ci-oss-test-infra-autobump-prow-for-auto-deploy/1428054460566867968/podinfo.json#1629309748149434
```


podinfo was uploaded 19s after finished.json

**Comment by chaodaiG** [comment]
This should be fixed by https://github.com/GoogleCloudPlatform/testgrid/pull/657
/close
