### ISSUE TITLE
Make summary=beta the default behavior for testgrid.k8s.io

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/testgrid#73]
Testgrid is rolling out a new method of creating summaries that is:
* Open source
* Written in golang
* Running on kubernetes

You can view this by:
1) Navigating to a dashboard
2) Adding `?summary=beta` to the URL, for example: https://testgrid.k8s.io/sig-testing-misc?summary=beta

Any problems? They can be fixed by:
* Sending a PR to fix the code: https://github.com/GoogleCloudPlatform/testgrid/tree/master/cmd/summarizer
* Commenting on this issue, or
* Creating a new issue that refers back to this one.

Thanks!

**Comment by justaugustus** [comment]
FYI: @tpepper @calebamiles @alejandrox1 @alenkacz
xref: https://kubernetes.slack.com/archives/C09QZ4DQB/p1576273636010800

**Comment by fejta** [comment]
Done
